### ISSUE TITLE
Cannot list gpg keys

### ISSUE THREAD

**Issue by lakuapik** [owenvoke/gh-gpg-key#1]
when i try run `gh gpg-key list` it returns an error as show below:

![image](https://user-images.githubusercontent.com/20186786/135863642-baf5a943-1c38-44ef-a97d-d6ff58652154.png)

my gpg and ssh keys:

![image](https://user-images.githubusercontent.com/20186786/135863921-b920f4f2-41a9-47c8-aa3f-7c5f679f6a5a.png)

**Comment by owenvoke** [comment]
Apologies for the delay in getting back to you. I'm not entirely sure why this has happened, however I'm pleased to say that the functionality should be in the next release of the GitHub CLI core. 👍🏻 Therefore I'm going to deprecate this extension as it will no longer be necessary.

Thanks for reporting your issue, but I'm going to close this and direct you to the core PR. 👍🏻
https://github.com/cli/cli/pull/3822
